//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by EmperorOfDragons.rc
//
#define IDC_MYICON                      2
#define IDD_EMPEROROFDRAGONS_DIALOG     102
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDS_HELLO                       106
#define IDS_DISCRYPTION                 106
#define IDI_EMPEROROFDRAGONS            107
#define IDI_SMALL                       108
#define IDC_EMPEROROFDRAGONS            109
#define IDC_IDEDIT                      110
#define IDS_INITIALIZEGAME              110
#define IDC_PWEDIT                      111
#define IDS_CONNECTLOGINSERVER          111
#define IDC_MAINCHATEDIT                112
#define IDS_TIMEOUT_RETRY               112
#define IDC_CHARACTERNAMEEDIT           113
#define IDS_CANNOTCONNECTELOGINSERVER   113
#define IDC_PARTYNAMEEDIT               114
#define IDS_REQUESTLOGINRESULT          114
#define IDS_TIMEOUT_RETRYREQUESTLOGINRESULT 115
#define IDS_CANNOTDOWNLOADLOGINRESULT   116
#define IDS_CANNOTCONNECTEGAMESERVER    117
#define IDS_LOGINGAMESERVER_COUNTDOWNMESSAGE 118
#define IDS_LOGINGAMESERVER             119
#define IDS_CANCELCONNECT               120
#define IDS_EMPTY_IDORPASSWORD          121
#define IDS_CONNECTEDGAMESERVER         122
#define IDS_CLOSEGAME                   123
#define IDS_TOOLTIP_LOGIN               124
#define IDS_TOOLTIP_ENDGAME             125
#define IDS_FAILEDCREATECHARACTER       126
#define IDS_EMPTYCHARACTERSLOT          127
#define IDR_MAINFRAME                   128
#define IDS_NONECHAR                    128
#define IDS_LEVELSTARSTRING             129
#define IDS_CONFIRMDELETECHARACTER      130
#define IDC_ARROWCURSOR                 131
#define IDS_DELETINGCHARACTER           131
#define IDS_REMOVEDCHARACTER            132
#define IDS_FAILEDSENDMESSAGETOSERVER   133
#define IDS_LOGINFAIL_INVALIDID         134
#define IDS_LOGINFAIL_ALREADYCONNECTED  135
#define IDD_XMESSAGEDIALOG              136
#define IDS_LOGINFAIL_INVALIDPASSWORD   136
#define IDS_LOGINFAIL_UNKNOWNERROR      137
#define IDS_WSAASYNCERROR               138
#define IDS_FAILEDSOCKETCONNECT         139
#define IDS_FAILEDRECIEVEPACKET         140
#define IDS_DISCONNECTEDLOGINSERVER     141
#define IDS_DISCONNECTEDGAMESERVER      142
#define IDS_ADMINCLOSEGAME              143
#define IDD_SELECTDEVICE                144
#define IDS_CLOSEGAME_COUNTDOWN         144
#define IDD_COMMANDDIALOG               145
#define IDS_CLOSEMAINGAME               145
#define IDS_CLOSEGAMEANDRETURNTOCHARACTERSELECT 146
#define IDS_CC_EMPTYNEWCHARACTERNAME    147
#define IDS_CC_SHORTNEWCHARACTERNAME    148
#define IDS_NOTALLUSEBONUSPOINT         149
#define IDS_CONFIRMCREATENEWCHARACTER   150
#define IDI_EODSMALLICON                151
#define IDS_FSTT_WALKBUTTON             151
#define IDD_DEBUGWINDOW                 152
#define IDS_FSTT_PICKBUTTON             152
#define IDD_ADMINCOMMANDDIALOG          153
#define IDS_FSTT_CHARACTERINFOBUTTON    153
#define IDS_FSTT_MINIMAPBUTTON          154
#define IDS_FSTT_QUESTBUTTON            155
#define IDS_FSTT_BATTLEMODEBUTTON       156
#define IDS_FSTT_INVENTORYBUTTON        157
#define IDS_FSTT_SKILLBUTTON            158
#define IDS_FSTT_COMMUNITYBUTTON        159
#define IDS_FSTT_OPTIONBUTTON           160
#define IDS_FSTT_INNEREXPVALUE          161
#define IDS_FSTT_OVERCROWDING           162
#define IDS_FSTT_STATUSVIEWCHANGEBUTTON 163
#define IDS_FSTT_ICONWINDOW             164
#define IDS_FSTT_MINIMIZEBUTTON         165
#define IDS_FSTT_QUICKSLOTBUTTON        166
#define IDS_FSTT_HEATH                  167
#define IDS_FSTT_INNER                  168
#define IDS_FSTT_STAMINA                169
#define IDS_FSTT_SOUL                   170
#define IDS_FSTT_HEART                  171
#define IDS_FSTT_RUNBUTTON              172
#define IDS_FSTT_PEACEMODEBUTTON        173
#define IDS_FAILEDCREATENEWCHARACTER    174
#define IDS_FAILEDSELECTCHARACTER       175
#define IDS_FAILEDDELETECHARACTER       176
#define IDS_SUCCESSSELECTCHARACTER      177
#define IDS_SUCCESSDELETECHARACTER      178
#define IDS_MMTT_ZOOMIN                 179
#define IDS_MMTT_ZOOMOUT                180
#define IDS_WINDOW_MINIMIZE             181
#define IDS_QSTT_NEXT                   182
#define IDS_QSTT_PREV                   183
#define IDS_QSTT_TYPECHANGE             184
#define IDS_CHATWINMAX                  185
#define IDS_CHATWINMIN                  186
#define IDS_QUESTW_INGQUEST             187
#define IDS_QUESTW_ENDQUEST             188
#define IDS_NAME                        189
#define IDS_CLASS                       190
#define IDS_ATTACKPOWER                 191
#define IDS_ATTACKSUCCESSLEVEL          192
#define IDS_WEIGHT                      193
#define IDS_REQUESTVALUE                194
#define IDS_EFFECT                      195
#define IDS_LEVELNAME_0                 196
#define IDS_LEVELNAME_1                 197
#define IDS_LEVELNAME_2                 198
#define IDS_LEVELNAME_3                 199
#define IDS_LEVELNAME_4                 200
#define IDS_LEVELNAME_5                 201
#define IDS_LEVELNAME_6                 202
#define IDS_LEVELNAME_7                 203
#define IDS_LEVELNAME_8                 204
#define IDS_LEVELNAME_9                 205
#define IDS_LEVELNAME_10                206
#define IDS_LEVELNAME_11                207
#define IDS_LEVELNAME_12                208
#define IDS_LEVELNAME_13                209
#define IDS_LEVELNAME_14                210
#define IDS_LEVELNAME_15                211
#define IDS_LEVELNAME_16                212
#define IDS_LEVELNAME_17                213
#define IDS_LEVELNAME_18                214
#define IDS_LEVELNAME_19                215
#define IDS_LEVELNAME_20                216
#define IDS_GROUPNAME_0                 217
#define IDS_GROUPNAME_1                 218
#define IDS_GROUPNAME_2                 219
#define IDS_GROUPNAME_3                 220
#define IDS_GROUPNAME_4                 221
#define IDS_GROUPNAME_5                 222
#define IDS_GROUPNAME_6                 223
#define IDS_GROUPNAME_7                 224
#define IDS_GROUPNAME_8                 225
#define IDS_GROUPNAME_9                 226
#define IDS_GROUPNAME_10                227
#define IDS_GROUPNAME_11                228
#define IDS_GROUPNAME_12                229
#define IDS_INVALIDCHARACTERNAME        229
#define IDS_USEWEAPON                   230
#define IDS_ZENWASTESTRING              231
#define IDS_REQUIREMENT                 232
#define IDC_DRIVER_COMBO                1000
#define IDC_ADAPTER_COMBO               1001
#define IDC_FILLMODECOMBO               1002
#define IDC_FULLSCREENMODES_COMBO       1003
#define IDC_MODES_COMBO                 1003
#define IDC_FOGCHECK                    1003
#define IDC_VIEWLOCALUSERCOORDBUTTON    1004
#define IDC_VIEWCOMMANDLISTBUTTON       1005
#define IDC_RUNCOMMANDBUTTON            1006
#define IDC_SCRINFOCHECK                1007
#define IDC_AXISCHECK                   1008
#define IDC_OBJECTVIEWCHECK             1009
#define IDC_FRUSTUMVIEWCHECK            1010
#define IDC_MYSETTINGCHECK              1011
#define IDC_WINDOWED_CHECKBOX           1012
#define IDC_VIEWLENSFLARECHECK          1012
#define IDC_USERLISTCHECK               1013
#define IDC_FULLSCREEN_TEXT             1014
#define IDC_MOBLISTCHECK                1014
#define IDC_FARPLANEEDIT                1015
#define IDC_WINDOW                      1016
#define IDC_USERCULLINGCHECK            1016
#define IDC_WINDOW2                     1017
#define IDC_MOVEXZEDITX                 1017
#define IDC_DEBUGSTRINGLIST             1017
#define IDC_FULLSCREEN                  1018
#define IDC_MOVEXZEDITZ                 1018
#define IDC_CLEARBUTTON                 1018
#define IDC_MOVETOUSERNAME              1019
#define IDC_MOVETOMOBNAME               1020
#define IDC_COMMANDHISTORYLIST          1021
#define IDC_OBBCHECK                    1022
#define IDC_LIGHTMODELCHECK             1023
#define IDC_TARGETPOSITIONCHECK         1024
#define IDC_TERRAINRENDERTIMECHECK      1025
#define IDC_TERRAINNORMALCHECK          1026
#define IDC_EDITW                       1027
#define IDC_USETEXTURECHECK             1027
#define IDC_EDITH                       1028
#define IDC_ENVSETLIST                  1028
#define IDC_REDSLIDER                   1029
#define IDC_GREENSLIDER                 1030
#define IDC_BLUESLIDER                  1031
#define IDC_ALPHASLIDER                 1032
#define IDC_REDEDIT                     1033
#define IDC_GREENEDIT                   1034
#define IDC_BLUEEDIT                    1035
#define IDC_ALPHAEDIT                   1036
#define IDC_VALUEEDIT                   1037
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1034
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
